# fly.toml app configuration file generated for projectmotor-hidden-dew-4544 on 2024-12-29T14:26:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'projectmotor-hidden-dew-4544'
primary_region = 'otp'

[build]
  [build.args]
    GO_VERSION = '1.21.5'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
