version: "3"

tasks:
  migrate-create:
    cmds:
      - "migrate create -ext sql -dir database/migrations -seq {{.CLI_ARGS}}"
    silent: true
  migrate-up:
    cmds:
      - migrate -database '{{.DATABASE_URL}}' -path database/migrations up
    requires:
      vars: [DATABASE_URL]
    silent: true
  migrate-down:
    cmds:
      - migrate -database '{{.DATABASE_URL}}' -path database/migrations down
    requires:
      vars: [DATABASE_URL]
    silent: true
  test:
    cmds:
      - templ generate && go test ./... -count=1
    silent: true
